name: game
on:
  push:
    branches:
      - master
      
env:
  name: "Sniper elite 3"
  comment: "Sniper elite 3"
  url: "https://pixeldrain.com/api/file/7BQUevP8?download"
  file_name: "OG13360B-TCLSCBLA.part1.rar"
  piece_size: 10
      
jobs:
  create:
    runs-on: ubuntu-latest
    steps:

      - name: Update apt
        run: sudo apt update

      - name: Install aria2 and mktorrent
        run: sudo apt-get install -y aria2 mktorrent

      - name: Download file using aria2 (16 connections & 16 splits)
        run: aria2c -x16 -s16 -k1M -o "$file_name" "$url"

      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"

      - name: Upload torrent file
        uses:  actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
